# generated by Git for Windows
# test -f ~/.profile && . ~/.profile
# test -f ~/.bashrc && . ~/.bash
source ~/.bashrc
alias proj="cd c:/users/karll/projects"
alias gs="git status"

alias kvast="proj; cd kvastu"
alias master="proj; cd master"
alias notes="cd C:/Users/karll/notes"
# eval "$(conda shell.bash hook)"
#i conda activate base
